### PR TITLE
Issues from 14 to 17 

### PR DESCRIPTION
**Pull request by conema**
#14 #15 #16 #17 resolved
Minor changes to lightning

Waiting for @Rosmaninho's tests

### CODE REVIEW

**Comment by Rosmaninho** [comment]
Weird, it's failing to install because the theme appears as corrupt.
I unzipped the folders and ziped the chrome file as chrome.xpi and it failed to install. Both of them.

**Comment by Rosmaninho** [comment]
small niggle

One final niggle remaining, between the Calendar and Tasks and the Mail tabs there's that little highlighted difference in color in the button to restore column order and selecting items to show.

**Comment by Rosmaninho** [comment]
Another one is:

gradient

Never seen modifications of that in any theme so I'm not sure if it's possible...

**Comment by Rosmaninho** [comment]
By the way, I created a couple of crappy Firefox Personas using their web-based theme creator.

https://addons.mozilla.org/en-US/firefox/addon/monterail-inspired/
https://addons.mozilla.org/en-US/firefox/addon/monterail-dark/
https://addons.mozilla.org/en-US/firefox/addon/monterail-full-dark/

If you ever wish to do Monterail themes for Firefox, tell me and I'll remove mine or change their names to something that doesn't conflict it so that you get full credit. You're way too good at this and I would prefer to see a superior version done by you anyway. :)

**Comment by conema** [comment]
> 
> 
> And still can't select original Monterail even in default theme.
> still

Yeah, this is the "Installation fail/Theme didn't change in Thunderbird 60" bug in the FAQ at its bests, unluckily this is a TB 60 bug.



> 
> 
> By the way, I created a couple of crappy Firefox Personas using their web-based theme creator.
> 
> https://addons.mozilla.org/en-US/firefox/addon/monterail-inspired/
> https://addons.mozilla.org/en-US/firefox/addon/monterail-dark/
> https://addons.mozilla.org/en-US/firefox/addon/monterail-full-dark/
> 
> If you ever wish to do Monterail themes for Firefox, tell me and I'll remove mine or change their names to something that doesn't conflict it so that you get full credit. You're way too good at this and I would prefer to see a superior version done by you anyway. :)

I think they are perfect, with the new theme API we cannot edit a lot.

> 
> 
> Another one is:
> 
> gradient
> 
> Never seen modifications of that in any theme so I'm not sure if it's possible...

Yes, but I'll work on that in another update (the one that will make the calendar 100% dark)

> 
> 
> small niggle
> 
> One final niggle remaining, between the Calendar and Tasks and the Mail tabs there's that little highlighted difference in color in the button to restore column order and selecting items to show.

Working on that, I'll update this when it's ready!

PS: Is the dark version ok?

**Comment by conema** [comment]
@Rosmaninho fix is ready!

PS: thanks for your help

**Comment by Rosmaninho** [comment]
Great job!! It's fixed and nice.
I can't pick any more niggles because it's looking perfect now. :)

Both Monterail Dark and Full Dark are working perfectly now. And you also managed to clear the conflicts with Monterail from Paenglab. It's possible to change to that one as well.

**Comment by Rosmaninho** [comment]
> > By the way, I created a couple of crappy Firefox Personas using their web-based theme creator.
> > https://addons.mozilla.org/en-US/firefox/addon/monterail-inspired/
> > https://addons.mozilla.org/en-US/firefox/addon/monterail-dark/
> > https://addons.mozilla.org/en-US/firefox/addon/monterail-full-dark/
> > If you ever wish to do Monterail themes for Firefox, tell me and I'll remove mine or change their names to something that doesn't conflict it so that you get full credit. You're way too good at this and I would prefer to see a superior version done by you anyway. :)
> 
> I think they are perfect, with the new theme API we cannot edit a lot.

Yup, but with your knowledge of CSS I don't know if it's possible to do better outside of their editor. I'm annoyed because they add a shadow in the bookmark toolbar and make any text there look fuzzy. it's awful for dark text. And it doesn't change the highlight on the active tab.

> 
> > Another one is:
> > gradient
> > Never seen modifications of that in any theme so I'm not sure if it's possible...
> 
> Yes, but I'll work on that in another update (the one that will make the calendar 100% dark)

Awesome. :) 
But for Monterail Dark it would be nice to  remove that gradient as well. it doesn't fit with Quantum themes.

> PS: Is the dark version ok?

Yes, it looks great. I think Monterail FullDark gives more work because you actually need to change more small things to make it fully dark.

There's some things on the Today Pane that also could use some darkening.

one more

the treecolpicker in the today pane is not dark. I don't think this needs changes in Monterail Dark, but in Monterail FullDark it should be the same color as the other treecolpickers?

and the "Please select a calendar that supports tasks" box maybe could also have the same color as other boxes...

**Comment by Rosmaninho** [comment]
Looking good! :D

**Pull request merged**
